Upgrade celery version and related libs
Hoping to help for issue of beat being unable to recover from
connection error (only solution seems to be docker restart)
It seems to be linked to https://github.com/celery/celery/issues/3921

Traces we got:
{
    "asctime": "2019-10-18 09:28:52,092",
    "levelname": "ERROR",
    "process": 1,
    "name": "celery.beat",
    "message": "Message Error: Couldn't apply scheduled task poller: [Errno -3] Try again
['  File \"/usr/bin/celery\", line 11, in <module>\
    sys.exit(main())\
', '  File \"/usr/lib/python2.7/site-packages/celery/__main__.py\", line 14, in main\
    _main()\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/celery.py\", line 326, in main\
    cmd.execute_from_commandline(argv)\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/celery.py\", line 488, in execute_from_commandline\
    super(CeleryCommand, self).execute_from_commandline(argv)))\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/base.py\", line 281, in execute_from_commandline\
    return self.handle_argv(self.prog_name, argv[1:])\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/celery.py\", line 480, in handle_argv\
    return self.execute(command, argv)\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/celery.py\", line 412, in execute\
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/base.py\", line 285, in run_from_argv\
    sys.argv if argv is None else argv, command)\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/base.py\", line 368, in handle_argv\
    return self(*args, **options)\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/base.py\", line 244, in __call__\
    ret = self.run(*args, **kwargs)\
', '  File \"/usr/lib/python2.7/site-packages/celery/bin/beat.py\", line 107, in run\
    return beat().run()\
', '  File \"/usr/lib/python2.7/site-packages/celery/apps/beat.py\", line 79, in run\
    self.start_scheduler()\
', '  File \"/usr/lib/python2.7/site-packages/celery/apps/beat.py\", line 107, in start_scheduler\
    service.start()\
', '  File \"/usr/lib/python2.7/site-packages/celery/beat.py\", line 558, in start\
    interval = self.scheduler.tick()\
', '  File \"/usr/lib/python2.7/site-packages/celery/beat.py\", line 279, in tick\
    self.apply_entry(entry, producer=self.producer)\
', '  File \"/usr/lib/python2.7/site-packages/celery/beat.py\", line 225, in apply_entry\
    exc, traceback.format_stack(), exc_info=True)\
']",
    "exc_info": "Traceback (most recent call last):
  File \"/usr/lib/python2.7/site-packages/celery/beat.py\", line 222, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File \"/usr/lib/python2.7/site-packages/celery/beat.py\", line 328, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File \"/usr/lib/python2.7/site-packages/celery/beat.py\", line 320, in apply_async
    **entry.options)
  File \"/usr/lib/python2.7/site-packages/celery/app/task.py\", line 536, in apply_async
    **options
  File \"/usr/lib/python2.7/site-packages/celery/app/base.py\", line 737, in send_task
    amqp.send_task_message(P, name, message, **options)
  File \"/usr/lib/python2.7/site-packages/celery/app/amqp.py\", line 554, in send_task_message
    **properties
  File \"/usr/lib/python2.7/site-packages/kombu/messaging.py\", line 181, in publish
    exchange_name, declare,
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 527, in _ensured
    errback and errback(exc, 0)
  File \"/usr/lib/python2.7/contextlib.py\", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 419, in _reraise_as_library_errors
    sys.exc_info()[2])
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 414, in _reraise_as_library_errors
    yield
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 515, in _ensured
    reraise_as_library_errors=False,
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 405, in ensure_connection
    callback)
  File \"/usr/lib/python2.7/site-packages/kombu/utils/functional.py\", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 261, in connect
    return self.connection
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 802, in connection
    self._connection = self._establish_connection()
  File \"/usr/lib/python2.7/site-packages/kombu/connection.py\", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File \"/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py\", line 130, in establish_connection
    conn.connect()
  File \"/usr/lib/python2.7/site-packages/amqp/connection.py\", line 296, in connect
    self.transport.connect()
  File \"/usr/lib/python2.7/site-packages/amqp/transport.py\", line 123, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File \"/usr/lib/python2.7/site-packages/amqp/transport.py\", line 153, in _connect
    host, port, 0, socket.SOCK_STREAM, SOL_TCP,
SchedulingError: Couldn't apply scheduled task poller: [Errno -3] Try again",
    "env": "dev"
}